### ISSUE TITLE
missing auto connect.h

### ISSUE THREAD

**Issue by tbillion** [cvilasis69/DuinoMiner-ESP32#1]
modesp32duo:132:10: fatal error: AutoConnect.h: No such file or directory
 #include <AutoConnect.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
exit status 1
AutoConnect.h: No such file or directory

**Comment by cvilasis69** [comment]
The included PlatformIO INI file contains this dependency. VSC/PlatformIO downloads the required libraries to resolve this include.
But if you're trying to use Arduino IDE then you'll need to manually download libraries.

**Comment by cvilasis69** [comment]
Worked?

**Comment by tbillion** [comment]
![image](https://user-images.githubusercontent.com/16172731/181865120-7e88df14-9809-49ba-b8eb-7b87e75dba76.png)
why dies it need to be dependant on arduino esp core 2.01 to run as advertised i am using 2.04 and i suffer reduced speeds that flag in the wallet the yellow triangle says that i need 2.0.1 to have higher hash rates
